config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  resources :topics, only: [:index, :show]
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  # get 'pages/home'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  put 'sort', to: 'pages#sort'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'


end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1 }
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body, :topic_id

  belongs_to :topic
  has_many :comments, dependent: :destroy
  
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  before_action :set_topbar_topics, except: [:update, :create, :destroy, :toggle_status]
  layout "blog"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, site_admin: :all

  def index
    if logged_in?(:site_admin)
      @blogs = Blog.all.order(created_at: :desc).page(params[:page]).per(5)
    else
      @blogs = Blog.published.order(created_at: :desc).page(params[:page]).per(5)
    end
    @page_title = "My Portfolio Blog"
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    if logged_in?(:site_admin) || @blog.published?
      # here we have access to @blog.title because of the set_blog action below that is called as a before_action
      @blog = Blog.includes(:comments).friendly.find(params[:id])
      @comment = Comment.new

      @page_title = @blog.title
      @seo_keywords = @blog.title
    else
      redirect_to blogs_path, notice: "You are not allowed to see this, so sad"
    end
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Your post is now live.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Your post is now obliterated.' }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end
    redirect_to blogs_url, notice: 'post status has been updated'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body, :topic_id, :status)
    end

    def set_topbar_topics
      @topbar_topics = Topic.with_blogs
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def gravatar_helper user
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width: 60
  end

  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)

    options = {
      fenced_code_blocks: true,
      no_intra_emphasis: true,
      autolink: true,
      lax_html_blocks: true,
    }

    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end
end

app/views/blogs/_blog.html.erb
<div class="blog-post">
  <h2 class="blog-post-title"><%= link_to blog.title.upcase, blog %></h2>
  <p class="blog-post-meta">Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago</p>
  <p>
    <%= markdown blog.body %>
  </p>
  <% if logged_in?(:site_admin) %>
    <p class="blog-post-meta">
      <%= link_to blog.status, toggle_status_blog_path(blog), class: (blog.status == "draft" ? 'btn btn-secondary' : 'btn btn-primary') %> /
      <%= link_to 'Edit', edit_blog_path(blog), class: "btn btn-success" %> /
      <%= link_to_if(logged_in?(:site_admin), 'Delete Post', blog, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" ) %>
    </p>
  <% end  %>
</div>
<!-- /.blog-post -->

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <% blog.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, autofocus: true, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :topic_id %>
    <%= form.collection_select(:topic_id, Topic.all, :id, :title,
                               {
                                 include_blank: true
                               },
                               class: 'form-control'
                              )
    %>
  </div>

  <div class="form-group">
    <%= form.radio_button :status, 'draft' %>
    <%= form.label :status, 'Draft' %>

    <%= form.radio_button :status, 'published' %>
    <%= form.label :status, 'Published' %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, autofocus: true, class: 'form-control', rows: 5 %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-lg btn-primary btn-block" %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Edit Blog Post</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<!-- Blog Posts -->

<%= paginate @blogs %>

<%= render @blogs %>

<%= paginate @blogs, theme: 'twitter-bootstrap-4', class: "blog-pagination" %>

<!-- Blog Posts DONE -->


  <!-- <nav class="blog-pagination">
    <a class="btn btn-outline-primary" href="#">Older</a>
    <a class="btn btn-outline-secondary disabled" href="#">Newer</a>
  </nav> -->

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

app/views/blogs/show.html.erb
<h2>
  <strong>Title:</strong>
  <%= @blog.title %>
</h2>

<p>
  <%= @blog.topic.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= markdown @blog.body %>
</p>

<%= link_to '✎ Edit Post', edit_blog_path(@blog), class: "btn btn-success" if logged_in?(:site_admin) %>

<%= render 'comments/comment_form' %>

<!-- Start of comments -->
<div id="comments" data-blog-id="<%= @blog.id %>">
  <%= render @blog.comments %>
</div>
<!-- End of comments -->
<br>
<%= link_to '◀︎ Blog Index', blogs_path, class: "btn btn-warning" %>