config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  resources :topics, only: [:index, :show]
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  # get 'pages/home'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  put 'sort', to: 'pages#sort'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'


end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['name'].blank? }

  include Placeholder
  validates_presence_of :title, :body

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  def self.by_position
    order("position ASC")
  end

  def self.angular
    where(subtitle: 'ANGULAR')
  end

  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: 'Ruby on Rails') }
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:edit, :update, :show, :destroy]
  layout 'portfolio'
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all


  def index
    @portfolio_items = Portfolio.by_position
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end
    head :ok
  end

# the name of the def is the name of the view file angular.html.erb that passes the instance variable
  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def new
    @portfolio_item = Portfolio.new
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Your portfolio_item is now live.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    # whatever portfolio item id is it will find it
    # @portfolio_item = Portfolio.find(params[:id])
  end

  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'The record successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
  end

  def destroy
    # this will perform the lookup for the record
    # @portfolio_item = Portfolio.find(params[:id])
    # this will destroy the record
    @portfolio_item.destroy
    # This will redirect
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Your post is now obliterated.' }
    end
  end

  private
  # this params refactor follows our keeping code DRY
  def portfolio_params
    params.require(:portfolio).permit(:title,
                                      :subtitle,
                                      :body,
                                      :main_image,
                                      :thumb_image,
                                      technologies_attributes: [:id, :name, :_destroy]
                                      )
  end

  def set_portfolio_item
    @portfolio_item = Portfolio.find(params[:id])
  end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"
  end

# this method takes two arguements (img and type) then it says if img is provided (uploaded) return the image
# elseif type is thumb then use our image generator method from above
# else returns our main image
# then we call this from the view
  def portfolio_img img, type
    if img.is_a?(String)
      img
    elsif type == 'thumb'
      image_generator(height: '350', width: '200')
    else
      image_generator(height: '600', width: '400')
    end
  end
end

app/views/portfolios/_form.html.erb
<!-- Partial rendered from new.html.erb -->

<%= form_for(@portfolio_item) do |form| %>
  <% if @portfolio_item.errors.any? %>
    <% @portfolio_item.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, autofocus: true, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :subtitle %>
        <%= form.text_field :subtitle, autofocus: true, class: 'form-control' %>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload a main image file <%= form.file_field :main_image, style: 'display:none;' %>
        </label>
      </div>
      <div class="form-group">
        <label class="btn btn-primary">
          Upload a thumb image file <%= form.file_field :thumb_image, style: 'display:none;' %>
        </label>
      </div>

    </div>

  <div class="col-md-6">
    <div class="form-group">
      <%= form.label :body %>
      <%= form.text_area :body, autofocus: true, class: 'form-control', rows: 5 %>
    </div>
  </div>
</div>

  <hr>

  <div class="col-md-12">
    <h2>Technologies Used</h2>
    <div>
      <%= form.fields_for :technologies do |technology_form| %>
        <%= render 'technology_fields', f: technology_form %>
      <% end %>
    </div>
  </div>

  <div>
    <%= link_to_add_association 'Add Technology', form, :technologies %>
  </div>

  <div class="actions">
    <%= form.submit 'Save Portfolio Item', class: "btn btn-lg btn-primary btn-block" %>
    <hr>
    <%= link_to "View All Portfolio Items", portfolios_path, class: "btn btn-lg btn-secondary btn-block" %>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4">
  <div class="card mb-4 box-shadow" data-id="<%= portfolio_item.id %>">
    <%= image_tag portfolio_img(portfolio_item.thumb_image.to_s, 'thumb'), width: '100%' %>
    <div class="card-body">
      <span> <%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %> </span>
      <h3 class="card-title"><%= portfolio_item.subtitle %></h3>
        <div class="d-flex justify-content-between align-items-center">
          <div class="btn-group">
            <%= link_to "Edit", edit_portfolio_path(portfolio_item), class: "btn btn-sm btn-outline-secondary" if logged_in?(:site_admin) %>
            <%= link_to 'Delete Post', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-secondary" if logged_in?(:site_admin) %>
          </div>
          <small class="text-muted">9 mins</small>
        </div>
    </div>
  </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true, class: 'form-control' %>
  <%= link_to_remove_association 'Remove Item', f %>
</div>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items </h1>

<%= link_to "Create New Item", new_portfolio_path if logged_in?(:site_admin) %>

<% @angular_portfolio_items.each do |portfolio_item| %>
  <h2><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></h2>
  <p><%= portfolio_item.subtitle %></p>
  <p><%= portfolio_item.body %></p>
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
  <%= link_to "Edit", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %>
  <%= link_to 'Delete Post', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>
<% end %>

app/views/portfolios/edit.html.erb
<div class="container portfolio-form">
  <h1>Edit this Portfolio Item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row sortable">
      <%= render partial: 'portfolio_item', collection: @portfolio_items %>
    </div>
  </div>
</div>

<!-- <h1>Portfolio Items </h1> -->

<!-- <a href="portfolios/new">Create New Item</a> -->

<!-- link_to "link for an emaik", new_portfolio_url, subdomain: 'shmoover.com' in an email you need to send a url path so that it can link to your site properly -->

app/views/portfolios/new.html.erb
<div class="container portfolio-form">
  <h1>Create new Portfolio Item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
  
</div>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
  <div class="row">
    <div class="col-md-7">
       <%= image_tag @portfolio_item.main_image.to_s, width: '100%' %>
    </div>

    <div class="col-md-5">
      <h1> <%= @portfolio_item.title %> </h1>
      <hr>
      <em> <%= @portfolio_item.subtitle %> </em>
      <p> <%= @portfolio_item.body %> </p>
      <hr>
      <h3> Technologies Used: </h3>

      <% @portfolio_item.technologies.each do |t| %>
      <p><%= t.name %></p>
      <% end %>
      <%= link_to "View All Portfolio Items", portfolios_path %>
      <% if logged_in?(:site_admin) %>
        <div class="">
          <%= link_to "Edit Item", edit_portfolio_path(@portfolio_item), class: 'btn btn-warning' %>
        </div>
      <% end %>
    </div>
  </div>
</div>