config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  resources :topics, only: [:index, :show]
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  # get 'pages/home'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  put 'sort', to: 'pages#sort'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'


end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner">
  <p class="app-footer"> <%= copyright_generator %> <a href="https://github.com/misraelson"><%= fa_icon "github" %> GitHub </a> <a href="https://www.linkedin.com/in/matthew-israelson/"><%= fa_icon "linkedin" %> LinkedIn</a> </p>

  </div>
</footer>

app/views/shared/_application_nav.html.erb
<header class="masthead clearfix">
  <div class="container">
    <nav class="nav-masthead navbar-expand-md justify-content-center gradient-navbar">
      <button class="navbar-toggler navbar-dark" type="button" data-toggle="collapse" data-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarsExample03">
        <%= nav_helper 'nav-link', 'span' %>
        <%= link_to "About Me", "#about-me", class: 'nav-link' %>
        <%= link_to "Skills", "#skills", class: 'nav-link' %>
        <!-- <%= login_helper "text-white btn btn-sm btn-outline-secondary" %> -->
      </div>
    </nav>
  </div>
</header>

<script>
document.querySelector( ".navbar-toggler" )
  .addEventListener( "click", function() {
    this.classList.toggle( "active" );
  });
</script>

app/views/shared/_blog_block_features.html.erb
<div class="row mb-2">
  <div class="col-md-6">
    <div class="card flex-md-row mb-4 box-shadow h-md-250">
      <div class="card-body d-flex flex-column align-items-start">
        <strong class="d-inline-block mb-2 text-primary">World</strong>
        <h3 class="mb-0">
          <a class="text-dark" href="#">Featured post</a>
        </h3>
        <div class="mb-1 text-muted">Nov 12</div>
        <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
        <a href="#">Continue reading</a>
      </div>
        <a href="https://placeholder.com"><img src="http://via.placeholder.com/200x250" class="card-img-right flex-auto d-none d-md-block" alt="Card image cap"></a>
    </div>
  </div>
  <div class="col-md-6">
    <div class="card flex-md-row mb-4 box-shadow h-md-250">
      <div class="card-body d-flex flex-column align-items-start">
        <strong class="d-inline-block mb-2 text-success">Design</strong>
        <h3 class="mb-0">
          <a class="text-dark" href="#">Post title</a>
        </h3>
        <div class="mb-1 text-muted">Nov 11</div>
        <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
        <a href="#">Continue reading</a>
      </div>
        <a href="https://placeholder.com"><img src="http://via.placeholder.com/200x250" class="card-img-right flex-auto d-none d-md-block" alt="Card image cap"></a>
    </div>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= copyright_generator %>
  </p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_jumbotron.html.erb
<div class="jumbotron p-3 p-md-5 text-white rounded bg-gradient-info">
  <div class="row">
    <div class="col-md-8 px-0">
      <h1 class="display-4 font-italic">How to make a 'real' good first impression as a tech freelancer</h1>
      <p class="lead my-3">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what's most interesting in this post's contents.</p>
      <p class="lead mb-0"><a href="blogs/first_article.erb" class="text-white font-weight-bold">Continue reading...</a></p>
    </div>
    <div class="col-md-4 px-0">
      <a href="blogs/first_article.erb"><img src="tech_interview_hh" class="img-fluid img-thumbnail"></a>
    </div>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<!-- START OF NAV -->
  <div class="container">
    <header class="blog-header py-3">
      <div class="row flex-nowrap justify-content-between align-items-center">
        <div class="col-4 pt-1">
          <%= nav_helper 'text-muted', 'span' %>
        </div>
        <div class="col-4 text-center">
          <a class="blog-header-logo text-dark" href="#">Sens : Meaning</a>
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
          <!-- <a class="text-muted" href="#">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3"><circle cx="10.5" cy="10.5" r="7.5"></circle><line x1="21" y1="21" x2="15.8" y2="15.8"></line></svg>
          </a> -->
          <%= login_helper "btn btn-sm btn-outline-secondary" %>
        </div>
      </div>
    </header>
    <!-- End of NAV -->

app/views/shared/_blog_sidebar.html.erb
<!-- SIDEBAR -->

<aside class="col-md-4 blog-sidebar">
  <!-- <div class="p-3 mb-3 bg-light rounded">
    <h4 class="font-italic">About</h4>
    <p class="mb-0">Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
  </div> -->

  <div class="p-3">
    <h4 class="font-italic">Archives</h4>
    <ol class="list-unstyled mb-0">
      <li><a href="#">May 2018</a></li>
    </ol>
  </div>
  <div class="p-3">
    <h4 class="font-italic">Topics</h4>
    <ol class="list-unstyled mb-0">
      <p>
        <% @topbar_topics.each do |topic| %>
          <%= link_to topic.title, topic_path(topic), class: "p-2 text-muted" %>
        <% end %>
      </p>
    </ol>
  </div>

  <div class="p-3">
    <h4 class="font-italic">Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://github.com/misraelson"><%= fa_icon "github" %> GitHub </a></li>
      <li><a href="https://www.linkedin.com/in/matthew-israelson/"><%= fa_icon "linkedin" %> LinkedIn</a></li>
    </ol>
  </div>
</aside><!-- /.blog-sidebar -->

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div> <%= link_to "Home", root_path %> </div>
  <div> <%= link_to "About", about_me_path %> </div>
  <div> <%= link_to "Contact", contact_path %> </div>
  <div> <%= link_to "Portfolio", portfolios_path %> </div>
  <div> <%= link_to "Blog", blogs_path %> </div>
</div>

app/views/shared/_portfolio_footer.html.erb
<!-- start of footer -->
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p>
      <%= copyright_generator %>
    </p>
  </div>
</footer>
<!-- end of foooter -->

app/views/shared/_portfolio_jumbotron.html.erb
<!-- jumbo start -->
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Portfolio</h1>
    <p class="lead text-muted">I'm a full-stack developer with a passion for building pixel-perfect responsive front-ends with robust RESTful Rails API backends. Check out some of the projects I've worked on below 👇</p>
    <p>
      <%= link_to 'Find out more about me', about_me_path, class: "btn btn-primary my-2" %>
      <%= link_to 'My Blog', blogs_path, class: "btn btn-secondary my-2" %>
    </p>
  </div>
</section>
<!-- jumbo end -->

app/views/shared/_portfolio_nav.html.erb
<!-- navbar start -->
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Here is some info from my birthchart: You have a tendency to be introspective and need some space and seclusion in order to pull up your strength. You may avoid the spotlight, and if you do find yourself in a public role, you tend to hide your true self behind that role! Because your will is directed inwards, you need to find a path for yourself that allows you to "get away from it all" at least some of the time. Honor your need to be alone with yourself, but avoid over-identifying with your inner world to the point that you truly feel alone in a crowd. You shine when you serve others in some way. Your compassion sets you apart from others, but try to work with it rather than let your compassion work against you by reinforcing your own sense of loneliness.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Explore</h4>
          <ul class="list-unstyled">
            <%= nav_helper 'text-white', 'li' %>
            <li> <%= login_helper "text-white btn btn-sm btn-outline-secondary" %> </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark box-shadow">
    <div class="container d-flex justify-content-between">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
        <strong>Responsive Web Design and Development</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>
<!-- navbar end -->