config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  resources :topics, only: [:index, :show]
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  # get 'pages/home'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  put 'sort', to: 'pages#sort'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="keywords" content="<%= @seo_keywords %>"/>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">

          <%= video_tag(
              'AbstractBokehPan.mp4',
              id: 'background',
              autoplay: true,
              loop: true,
              muted: true,
              poster: 'portfolio-background.jpg'
            )
            %>

          <!-- <div id="background"></div> -->

          <%= render "shared/application_nav" %>

          <%= yield %>

          <%= render "shared/application_footer" %>
          <!-- this alerts method is inside application_helper -->
          <%= alerts %>

          <%= source_helper("application") %>

        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="keywords" content="<%= @seo_keywords %>" />
    <%= stylesheet_link_tag    'blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'shared/blog_nav' %>

    <!-- Start of blog header -->
    <div class="nav-scroller py-1 mb-2">
      <nav class="nav d-flex justify-content-between">
          <% @topbar_topics.each do |topic| %>
            <a><%= link_to topic.title, topic_path(topic), class: "p-2 text-muted" %></a>
          <% end %>
      </nav>
    </div>
    <!-- End -->
    <% unless !current_page?('/blogs') %>
      <!-- Jumbotron -->
      <!-- <%= render 'shared/blog_jumbotron' %> -->
      <!-- Start of two block features -->
        <!-- <%= render 'shared/blog_block_features' %> -->
    <% end %>

    <!-- Blog Posts Header -->
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8 blog-main">
          <h3 class="pb-3 mb-4 font-italic border-bottom">
            From the Firehose
          </h3>
          <%= link_to 'Write a New Blog', new_blog_path, class: "btn btn-info" if logged_in?(:site_admin) %>
          <%= yield %>
        </div>

        <%= render 'shared/blog_sidebar' %>


      </div><!-- /.row -->
    </main><!-- /.container -->

    <%= render 'shared/blog_footer' %>

    <%= alerts %>

    <!-- This is for saying thanks for visiting from facebook etc -->
    <%= source_helper("blog") %>

  </body>
</html>

app/views/layouts/portfolio.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="keywords" content="<%= @seo_keywords %>" />

    <%= stylesheet_link_tag    'portfolios', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/portfolio_nav' %>

    <%= render 'shared/portfolio_jumbotron' unless logged_in?(:site_admin) %>

    <%= yield %>

    <%= render 'shared/portfolio_footer' %>

    <%= alerts %>

    <%= source_helper("application") %>
  </body>
</html>